import Head from "next/head";
import { useRef } from "react";
import {
  motion,
  useScroll,
  useSpring
} from "framer-motion";
import HeroComponent from "@/templates/LandingPage/components/HeroComponent";
import AboutComponent from "@/templates/LandingPage/components/AboutComponent";


const Index = () => {
  const ref = useRef(null);
  const { scrollYProgress, scrollXProgress } = useScroll({ target: ref });

  const scaleX = useSpring(scrollYProgress, {
    stiffness: 100,
    damping: 30,
    restDelta: 0.001
  });


  return (
    <>
      <Head>
        <title>kkn</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="w-full h-[500vh]" ref={ref}>
        <HeroComponent />
        <AboutComponent />
        <motion.div className="fixed left-0 right-0 h-[5px] bottom-[100px] bg-black" style={{ scaleX }} />
      </div>
    </>
  );
}

export default Index;
